### ISSUE TITLE
Trying to use excerpt for specific dates without any luck.

### ISSUE THREAD

**Issue by igenkin** [brandon-rhodes/python-jplephem#48]
I've downloaded the latest jup365.bsp and trying to create an excerpt file for specific dates, but gets errors:

```
C:\Temp>python -m jplephem excerpt 2021/1/1 2050/12/31 jup365.bsp jup_excerpt.bsp

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\jplephem\__main__.py", line 3, in <module>
    sys.stdout.write(main(sys.argv[1:]))
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\jplephem\commandline.py", line 56, in main
    lines = list(func(args))
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\jplephem\commandline.py", line 93, in excerpt
    write_excerpt(spk, output_file, args.start_date, args.end_date,
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\jplephem\excerpter.py", line 56, in write_excerpt
    excerpt = copy(old.read_array(
  File "C:\Users\admin\AppData\Roaming\Python\Python39\site-packages\jplephem\daf.py", line 146, in read_array
    data = f.read(8 * length)
ValueError: read length must be non-negative or -1
```

If I specify only 3,5 and 10 targets everything works fine, but not for 501 - 504 or any other targets, or if I do not specify targets at all. Not sure what I'm missing or doing wrong.

**Comment by brandon-rhodes** [comment]
I can confirm the problem! That file splits its coverage of each satellite into two segments, one for the early years and one for the later years, for example:

```
2305456.50..2450464.50  Type 2  Jupiter Barycenter (5) -> Io (501)
...
2450464.50..2524602.50  Type 2  Jupiter Barycenter (5) -> Io (501)
```

And the excerpt function, embarrassingly, does no bounds checking, so it gets a negative number when one of your dates is outside the range of one of the segments (which is unavoidable, of course, in this case).

I'll see if I can make it a bit smarter about cases like this!

**Comment by brandon-rhodes** [comment]
@igenkin — All right, I tweaked the code to handle better the case where a segment needs to be omitted entirely. Could you try out the new code and let me know if it works? You should be able to install it with:

    pip install -U https://github.com/brandon-rhodes/python-jplephem/archive/master.zip

**Comment by igenkin** [comment]
@brandon-rhodes - Works like a charm now! Thanks a lot!
(Had to manually uninstall jplephem before installing the updated version as it didn't want to update the file, but that's not an issue.)

**Comment by brandon-rhodes** [comment]
Thanks for doing that extra work to get the dev version installed for testing! I'll plan on a release tomorrow.
